// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application'

import AdminCurrentHeaderController from './admin_current_header_controller'
import HelloController from './hello_controller'

application.register('admin-current-header', AdminCurrentHeaderController)
application.register('hello', HelloController)
