name: Copilot Coding Agent Setup

on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml


env:
  RAILS_ENV: development
  PGHOST: "127.0.0.1"
  PGPORT: "5432"
  PGUSER: rails
  PGPASSWORD: password
  # DATABASE_URL: "postgres://rails:password@127.0.0.1:5432/may_is_bike_month_development"
  PARALLEL_TEST_FIRST_IS_1: true

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest

    # Read permission required to be able to clone the repository in setup
    permissions:
      contents: read

    services:
      postgres:
        image: postgres:17-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: may_is_bike_month_development
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
        # needed because the postgres container does not provide a healthcheck
        # tmpfs makes DB faster by using RAM
        options: >-
          --mount type=tmpfs,destination=/var/lib/postgresql/data
          --health-cmd pg_isready
          --health-interval 10s
          --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
      - name: Get CPU cores
        id: cpu-info
        run: |
          echo "cpu-cores=$(nproc)" >> $GITHUB_OUTPUT
          echo "cpu-cores=$(nproc)"
      # install system dependencies
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: google-chrome-stable curl gettext libvips
          version: 1.0
      - name: Checkout code
        uses: actions/checkout@v5
      # Install Ruby dependencies
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle install

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.tool-versions'
      
      # Copy .env so that ENV vars are in place (even if they're dummy values)
      - name: Copy .env.template
        run: cp .env.template .env
      
      - name: Debug environment variables
        run: |
          echo "PGHOST=${PGHOST}"
          echo "PGPORT=${PGPORT}"
          echo "PGUSER=${PGUSER}"
          echo "RAILS_ENV=${RAILS_ENV}"
          echo "DATABASE_URL=${DATABASE_URL}"

      - name: Set up database
        run: bin/rails db:create db:schema:load db:migrate db:seed

